server:
  port: 9090
spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
      - id: RES-SERVICE-A
        uri: http://localhost:9191
        predicates:
         - path=/a/**
         
      - id: RES-SERVICE-B
        uri: http://localhost:9292
        predicates:
         - path=/b/**  
         