server:
  port: 9191

 

spring:
  application:
    name: res-service-A
    
#Actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
        
#Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      RES-SERVICE-A:
       registerHealthIndicator: true
       eventConsumerBufferSize: 10
       failureRateThreshold: 50
       minimumNumberOfCalls: 5
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 5s
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowSize: 10
       slidingWindowType: COUNT_BASED